export const P = {
 
  AUTH_LOGOUT: 'AUTH_LOGOUT',

  // AUTH — roles
  AUTH_ROLES_LIST: 'AUTH_ROLES_LIST',
  AUTH_ROLES_GET: 'AUTH_ROLES_GET',
  AUTH_ROLES_CREATE: 'AUTH_ROLES_CREATE',
  AUTH_ROLES_UPDATE: 'AUTH_ROLES_UPDATE',
  AUTH_ROLES_DELETE: 'AUTH_ROLES_DELETE',
  AUTH_ROLES_CHANGE_USER: 'AUTH_ROLES_CHANGE_USER',

  // AUTH — permisos
  AUTH_PERMISSIONS_LIST: 'AUTH_PERMISSIONS_LIST',
  AUTH_ROLES_PERMISSIONS_GET: 'AUTH_ROLES_PERMISSIONS_GET',
  AUTH_ROLES_PERMISSIONS_SET: 'AUTH_ROLES_PERMISSIONS_SET',

  // AUTH — usuarios
  USERS_LIST: 'USERS_LIST',
  USERS_GET: 'USERS_GET',
  USERS_MY_ORGANIZATION: 'USERS_MY_ORGANIZATION',
  USERS_CREATE: 'USERS_CREATE',
  USERS_UPDATE: 'USERS_UPDATE',
  USERS_UPDATE_ROLES: 'USERS_UPDATE_ROLES',
  USERS_DEACTIVATE: 'USERS_DEACTIVATE',
  USERS_ACTIVATE: 'USERS_ACTIVATE',
  USERS_REVOKE_SESSIONS: 'USERS_REVOKE_SESSIONS',
  USERS_CHANGE_PASSWORD: 'USERS_CHANGE_PASSWORD',
  USERS_PROFILES_BATCH: 'USERS_PROFILES_BATCH',

  // ORG — organizaciones
  ORG_CREATE: 'ORG_CREATE',
  ORG_LIST: 'ORG_LIST',
  ORG_GET: 'ORG_GET',
  ORG_UPDATE: 'ORG_UPDATE',
  ORG_DELETE: 'ORG_DELETE',
  ORG_ACTIVATE: 'ORG_ACTIVATE',
  ORG_DEACTIVATE: 'ORG_DEACTIVATE',

  // ORG — sedes
  LOCATION_CREATE: 'LOCATION_CREATE',
  LOCATION_LIST: 'LOCATION_LIST',
  LOCATION_BY_ORG: 'LOCATION_BY_ORG',
  LOCATION_GET: 'LOCATION_GET',
  LOCATION_UPDATE: 'LOCATION_UPDATE',
  LOCATION_DELETE: 'LOCATION_DELETE',

  // DOCUMENTS
  DOC_CREATE: 'DOC_CREATE',
  DOC_LIST: 'DOC_LIST',
  DOC_GET: 'DOC_GET',
  DOC_UPDATE: 'DOC_UPDATE',
  DOC_DELETE: 'DOC_DELETE',
  DOC_ADD_VERSION: 'DOC_ADD_VERSION',
  DOC_FORCE_STATE: 'DOC_FORCE_STATE'
} as const;

export type PermissionCode = (typeof P)[keyof typeof P];
